# Generated by Django 2.1.4 on 2018-12-28 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0002_auto_20181228_0740'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='user_name',
        ),
        migrations.AlterField(
            model_name='users',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
